# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
     
    - name: Restore NuGet Packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Create Signature
      run: |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path Highlighter.Key.txt -Value '${{ secrets.CERTIFICATE }}'
        certutil -decode Highlighter.Key.txt Highlighter.Key.pfx
        & "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe" -i Highlighter.Key.pfx -p ${{ secrets.CERTIFICATE_PASS }} VS_KEY_D1B93F294121F939 
 
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PackageCertificateKeyFile=Highlighter.Key.pfx /p:PackageCertificatePassword=${{ secrets.CERTIFICATE_PASS }} ${{env.SOLUTION_FILE_PATH}} 

